// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	AccountDetails
	AccountCreateRequest
	AccountRequest
	AccountDeleteRequest
	AccountDeleteResponse
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountDetails struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *AccountDetails) Reset()                    { *m = AccountDetails{} }
func (m *AccountDetails) String() string            { return proto.CompactTextString(m) }
func (*AccountDetails) ProtoMessage()               {}
func (*AccountDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountDetails) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccountDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AccountCreateRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *AccountCreateRequest) Reset()                    { *m = AccountCreateRequest{} }
func (m *AccountCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountCreateRequest) ProtoMessage()               {}
func (*AccountCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountCreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AccountRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *AccountRequest) Reset()                    { *m = AccountRequest{} }
func (m *AccountRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()               {}
func (*AccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AccountDeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *AccountDeleteRequest) Reset()                    { *m = AccountDeleteRequest{} }
func (m *AccountDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountDeleteRequest) ProtoMessage()               {}
func (*AccountDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AccountDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AccountDeleteResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *AccountDeleteResponse) Reset()                    { *m = AccountDeleteResponse{} }
func (m *AccountDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountDeleteResponse) ProtoMessage()               {}
func (*AccountDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AccountDeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountDetails)(nil), "account.AccountDetails")
	proto.RegisterType((*AccountCreateRequest)(nil), "account.AccountCreateRequest")
	proto.RegisterType((*AccountRequest)(nil), "account.AccountRequest")
	proto.RegisterType((*AccountDeleteRequest)(nil), "account.AccountDeleteRequest")
	proto.RegisterType((*AccountDeleteResponse)(nil), "account.AccountDeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AccountService service

type AccountServiceClient interface {
	Create(ctx context.Context, in *AccountCreateRequest, opts ...grpc.CallOption) (*AccountDetails, error)
	Read(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountDetails, error)
	Update(ctx context.Context, in *AccountDetails, opts ...grpc.CallOption) (*AccountDetails, error)
	Delete(ctx context.Context, in *AccountDeleteRequest, opts ...grpc.CallOption) (*AccountDeleteResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Create(ctx context.Context, in *AccountCreateRequest, opts ...grpc.CallOption) (*AccountDetails, error) {
	out := new(AccountDetails)
	err := grpc.Invoke(ctx, "/account.AccountService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Read(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountDetails, error) {
	out := new(AccountDetails)
	err := grpc.Invoke(ctx, "/account.AccountService/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Update(ctx context.Context, in *AccountDetails, opts ...grpc.CallOption) (*AccountDetails, error) {
	out := new(AccountDetails)
	err := grpc.Invoke(ctx, "/account.AccountService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Delete(ctx context.Context, in *AccountDeleteRequest, opts ...grpc.CallOption) (*AccountDeleteResponse, error) {
	out := new(AccountDeleteResponse)
	err := grpc.Invoke(ctx, "/account.AccountService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountService service

type AccountServiceServer interface {
	Create(context.Context, *AccountCreateRequest) (*AccountDetails, error)
	Read(context.Context, *AccountRequest) (*AccountDetails, error)
	Update(context.Context, *AccountDetails) (*AccountDetails, error)
	Delete(context.Context, *AccountDeleteRequest) (*AccountDeleteResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*AccountCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Read(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Update(ctx, req.(*AccountDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Delete(ctx, req.(*AccountDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _AccountService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xbc, 0xb8,
	0xf8, 0x1c, 0x21, 0x4c, 0x97, 0xd4, 0x92, 0xc4, 0xcc, 0x9c, 0x62, 0x21, 0x3e, 0x2e, 0xa6, 0xcc,
	0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0xbc,
	0xc4, 0xdc, 0x54, 0x09, 0x26, 0xb0, 0x08, 0x98, 0x2d, 0x24, 0xc2, 0xc5, 0x9a, 0x9a, 0x9b, 0x98,
	0x99, 0x23, 0xc1, 0x0c, 0x16, 0x84, 0x70, 0x94, 0x1c, 0xb8, 0x44, 0xa0, 0x66, 0x39, 0x17, 0xa5,
	0x26, 0x96, 0xa4, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0xc0, 0x4d, 0x60, 0xc4, 0x66, 0x02,
	0x13, 0xb2, 0x09, 0x0a, 0x70, 0xd7, 0xc0, 0xf4, 0xa2, 0xb9, 0x46, 0x49, 0x0d, 0x6e, 0x87, 0x4b,
	0x6a, 0x4e, 0x2a, 0xc2, 0x0e, 0x74, 0x75, 0xea, 0x5c, 0xa2, 0x68, 0xea, 0x8a, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0xd1, 0x15, 0x1a, 0xcd, 0x64, 0x82, 0xdb, 0x19, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c,
	0x2a, 0xe4, 0xc4, 0xc5, 0x06, 0xf1, 0x80, 0x90, 0xac, 0x1e, 0x2c, 0xd8, 0xb0, 0x79, 0x4c, 0x4a,
	0x1c, 0x5d, 0x1a, 0x1a, 0x86, 0x4a, 0x0c, 0x42, 0x56, 0x5c, 0x2c, 0x41, 0xa9, 0x89, 0x29, 0x42,
	0x18, 0x4a, 0x88, 0xd0, 0x6b, 0xc3, 0xc5, 0x16, 0x5a, 0x90, 0x02, 0xb2, 0x1f, 0x97, 0x22, 0x7c,
	0xba, 0x3d, 0xb9, 0xd8, 0x20, 0x5e, 0xc6, 0x74, 0x3d, 0x4a, 0x90, 0x49, 0xc9, 0xe1, 0x92, 0x86,
	0x84, 0x94, 0x12, 0x43, 0x12, 0x1b, 0x38, 0xb1, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb0,
	0x8b, 0x45, 0xde, 0x3d, 0x02, 0x00, 0x00,
}
