// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	Account
	GetByIdRequest
	GetByEmailRequest
	CreateRequest
	DeleteRequest
	DeleteResponse
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetByIdRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetByIdRequest) Reset()                    { *m = GetByIdRequest{} }
func (m *GetByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*GetByIdRequest) ProtoMessage()               {}
func (*GetByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByEmailRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *GetByEmailRequest) Reset()                    { *m = GetByEmailRequest{} }
func (m *GetByEmailRequest) String() string            { return proto.CompactTextString(m) }
func (*GetByEmailRequest) ProtoMessage()               {}
func (*GetByEmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*GetByIdRequest)(nil), "account.GetByIdRequest")
	proto.RegisterType((*GetByEmailRequest)(nil), "account.GetByEmailRequest")
	proto.RegisterType((*CreateRequest)(nil), "account.CreateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "account.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "account.DeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AccountService service

type AccountServiceClient interface {
	GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*Account, error)
	GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*Account, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Account, error)
	Update(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := grpc.Invoke(ctx, "/account.AccountService/GetById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := grpc.Invoke(ctx, "/account.AccountService/GetByEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := grpc.Invoke(ctx, "/account.AccountService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Update(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := grpc.Invoke(ctx, "/account.AccountService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/account.AccountService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountService service

type AccountServiceServer interface {
	GetById(context.Context, *GetByIdRequest) (*Account, error)
	GetByEmail(context.Context, *GetByEmailRequest) (*Account, error)
	Create(context.Context, *CreateRequest) (*Account, error)
	Update(context.Context, *Account) (*Account, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetById(ctx, req.(*GetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetByEmail(ctx, req.(*GetByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Update(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _AccountService_GetById_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _AccountService_GetByEmail_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0xcb, 0xaa, 0x10, 0xbf, 0x04, 0xa2, 0x13, 0x63, 0x09, 0x17, 0xc9, 0x9e, 0xf4, 0xc2,
	0x41, 0x8d, 0x89, 0xd1, 0x8b, 0x56, 0x63, 0xbc, 0xd6, 0xf8, 0x00, 0x08, 0x73, 0x20, 0x69, 0x01,
	0x81, 0x9a, 0xf8, 0x48, 0xbe, 0xa5, 0xe9, 0x2e, 0x4b, 0xa1, 0x70, 0x9b, 0x3f, 0xdf, 0x37, 0x3b,
	0xf3, 0xcb, 0xc2, 0x8d, 0x93, 0xa4, 0xd8, 0xe4, 0x4d, 0x54, 0x56, 0x45, 0x53, 0x90, 0xd3, 0xa6,
	0x72, 0x01, 0xe7, 0x49, 0x87, 0xe4, 0x41, 0x64, 0xa9, 0x6f, 0x85, 0xd6, 0xe5, 0xf1, 0x52, 0x64,
	0x29, 0x11, 0x0e, 0xf3, 0x78, 0xcd, 0xbe, 0x50, 0x15, 0x15, 0xd3, 0x19, 0x8e, 0x78, 0x1d, 0x67,
	0x2b, 0xff, 0x40, 0x15, 0x75, 0x22, 0x43, 0x78, 0x6f, 0xdc, 0x3c, 0xff, 0xbe, 0xa7, 0x4b, 0xfe,
	0xde, 0x70, 0x3d, 0x9a, 0x25, 0xaf, 0x70, 0xaa, 0x14, 0xaf, 0x5b, 0xbd, 0x11, 0x75, 0xc3, 0xac,
	0xfe, 0xb0, 0x7b, 0xb8, 0x8b, 0x8a, 0xe3, 0x86, 0x8d, 0xcc, 0xec, 0x61, 0x4d, 0xed, 0x21, 0xfa,
	0xd6, 0x0b, 0xb8, 0x2f, 0xbc, 0xe2, 0x9d, 0x75, 0x7f, 0x8d, 0x10, 0x9e, 0x11, 0xd4, 0x65, 0x91,
	0xd7, 0xbc, 0xaf, 0xb8, 0xfe, 0x13, 0xf0, 0x5a, 0x20, 0x1f, 0x5c, 0xfd, 0x64, 0x09, 0xd3, 0x1d,
	0x9c, 0xf6, 0x3a, 0x9a, 0x47, 0x06, 0xe3, 0xf0, 0xde, 0xe0, 0xa4, 0x6b, 0xb4, 0x66, 0x39, 0xa3,
	0x47, 0x60, 0x77, 0x33, 0x05, 0x43, 0x6b, 0x1f, 0xc4, 0xa4, 0xfb, 0x16, 0xb6, 0xc6, 0x40, 0xe7,
	0x5d, 0x77, 0xc0, 0x65, 0xd2, 0x15, 0xc1, 0xfe, 0x2c, 0xd3, 0xad, 0x6b, 0xd4, 0x9d, 0xd4, 0x3f,
	0xc0, 0xd6, 0x40, 0x7a, 0xaf, 0x0c, 0x10, 0x06, 0xf3, 0x51, 0x5d, 0x93, 0x93, 0xb3, 0x2f, 0x5b,
	0xfd, 0xa5, 0x9b, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0xae, 0x78, 0x04, 0x5c, 0x02, 0x00,
	0x00,
}
